package entity;
// Generated Oct 16, 2016 11:58:40 AM by Hibernate Tools 4.3.1



/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon  implements java.io.Serializable {


     private int id;
     private Hoadon hoadon;
     private Sanpham sanpham;
     private int soluong;

    public Chitiethoadon() {
    }
    
    public Chitiethoadon(Hoadon hoadon, Sanpham sanpham) {
       this.hoadon = hoadon;
       this.sanpham = sanpham;
    }
    
    public Chitiethoadon(Hoadon hoadon, Sanpham sanpham,int soluong) {
       this.hoadon = hoadon;
       this.sanpham = sanpham;
    }

    public Chitiethoadon(int id, Hoadon hoadon, Sanpham sanpham,int soluong) {
       this.id = id;
       this.hoadon = hoadon;
       this.sanpham = sanpham;
       this.soluong = soluong;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Hoadon getHoadon() {
        return this.hoadon;
    }
    
    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    
     public int getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }




}


