package entity;
// Generated Oct 16, 2016 11:58:40 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private int id;
     private Taikhoan taikhoan;
     private Date ngaytao;
     private String tinhtrang;
     private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

    public Hoadon() {
    }

	
    public Hoadon(int id, Taikhoan taikhoan, String tinhtrang) {
        this.id = id;
        this.taikhoan = taikhoan;
        this.tinhtrang = tinhtrang;
    }
    public Hoadon(int id, Taikhoan taikhoan, Date ngaytao, String tinhtrang, Set<Chitiethoadon> chitiethoadons) {
       this.id = id;
       this.taikhoan = taikhoan;
       this.ngaytao = ngaytao;
       this.tinhtrang = tinhtrang;
       this.chitiethoadons = chitiethoadons;
    }
    
    public Hoadon(Taikhoan taikhoan, Date ngaytao, String tinhtrang) {
       this.taikhoan = taikhoan;
       this.ngaytao = ngaytao;
       this.tinhtrang = tinhtrang;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Taikhoan getTaikhoan() {
        return this.taikhoan;
    }
    
    public void setTaikhoan(Taikhoan taikhoan) {
        this.taikhoan = taikhoan;
    }
    public Date getNgaytao() {
        return this.ngaytao;
    }
    
    public void setNgaytao(Date ngaytao) {
        this.ngaytao = ngaytao;
    }
    public String getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public Set<Chitiethoadon> getChitiethoadons() {
        return this.chitiethoadons;
    }
    
    public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
        this.chitiethoadons = chitiethoadons;
    }




}


