package entity;
// Generated Oct 16, 2016 11:58:40 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private int ma;
     private String ten;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Loaisanpham() {
    }

	
    public Loaisanpham(int ma, String ten) {
        this.ma = ma;
        this.ten = ten;
    }
    public Loaisanpham(int ma, String ten, Set<Sanpham> sanphams) {
       this.ma = ma;
       this.ten = ten;
       this.sanphams = sanphams;
    }
   
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


